### ISSUE TITLE
[Discussion] The goat Easter Egg is causing concerns about security. 

### ISSUE THREAD

**Issue by whateverbee** [goodytwohews/dashify#10]
This line
[(https://github.com/goodytwohews/dashify/blob/e673b282c1f39fcb1cf5fcf2854f4d7f0ab68d5c/src/actions/internal-dash.js#L301)](https://github.com/goodytwohews/dashify/blob/e673b282c1f39fcb1cf5fcf2854f4d7f0ab68d5c/src/actions/internal-dash.js#L301)
inserts a goat emoji into the body of the internal dash, intended as an Easter Egg. 

There's concern that for uninitiated or less code-savvy users, this easter egg may flag a potential malicious script/corrupted extension, even though we know it's explicitly included. 

[![alt](https://screenshot.click/25-53-u2ger-hjmwx.png)](https://screenshot.click/25-53-u2ger-hjmwx.png)

Food for thought?

**Comment by goodytwohews** [comment]
Removed billy the hacker goat in [this commit](https://github.com/goodytwohews/dashify/commit/4f9d6da096a33ad0d409636dd5dd77ec28bf88a6). Will update to chrome store on Monday  👍
