### ISSUE TITLE
Recent billing amounts showing "Refund"

### ISSUE THREAD

**Issue by Brydom** [goodytwohews/dashify#8]
## The issue

Prioritize authentication information will show the word `Refund` instead of the amount if there is a refund available on one of the recent billing amounts.

![https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fscreenshot.click%2F15-50-1m7xg-2yygd.jpg](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fscreenshot.click%2F15-50-1m7xg-2yygd.jpg)

### Potential: Simple replace
Replace `Refund` in the string in the first string capture near lines 285, 286 within `internal-dash.js`

**Comment by goodytwohews** [comment]
Fixed in [this commit](https://github.com/goodytwohews/dashify/commit/ad0f1a6e7b876b93933b6f97a87d61663956421b) 👍
