### ISSUE TITLE
New UI Cards returning 'Null' because duplicate UI card ID's found

### ISSUE THREAD

**Issue by goodytwohews** [goodytwohews/dashify#9]
When updating from Dashify 1.1.1 to 1.2, next visit [this internal dash page](https://app.shopify.com/services/internal/shops/26581400), where Dashify found new UI Cards. I then refreshed Dashify to find an additional `Fulfillment Services` ID labelled `Null` and `Email Suppression` ID labelled 'Null' on the options.html page.

Looks like:

![](https://screenshot.click/16-58-tftec-uxl6w.jpg)

No errors in the console either: 

![](https://screenshot.click/16-12-eftvy-q3hoe.jpg)

Unsure on fix, but this is likely related to the `updateData` function that was added into v1.2 to save  user settings. My best guess is that the `forceUpdate` call is somehow duplicating the `Fulfillment Services` and `Email Suppression` ID's. 乁໒( ͒ ⌂ ͒ )७ㄏ

**Comment by Brydom** [comment]
Was not able to replicate on 1.2, might be something to do with the update from 1.1.2 to 1.2 itself and adding the functionality _to_ update

**Comment by Brydom** [comment]
Replicated on [this store](https://app.shopify.com/services/internal/shops/13346595) — v1.2 still

**Comment by Brydom** [comment]
After previous comment, [this store](https://app.shopify.com/services/internal/shops/9722926) re-added the duplicate settings. Looks like this is a consistent issue with the cards `fulfillment services` and `email suppressions`.

![https://screenshot.click/be-super-nice-iot23.png](https://screenshot.click/be-super-nice-iot23.png)

**Comment by Brydom** [comment]
[Commit](https://github.com/goodytwohews/dashify/commit/e673b282c1f39fcb1cf5fcf2854f4d7f0ab68d5c) for fix — essentially just checked to see if there were duplicates within the forced update arrays
